version: 0.0
os: linux # Ubuntu니까 linux로 설정.
files:
  - source: /
    destination: /home/ubuntu/deploy 
    overwrite: yes
permissions: 
  - object: /home/ubuntu/deploy #
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall: 
    - location: deploy.sh 
      timeout: 100 
      runas: root 