import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Footer from '../components/Footer';


//reactQuery recoil reactHotToast
import ReactQuery from '../components/recoilQueryToast/ReactQuery';
import Recoil from '../components/recoilQueryToast/Recoil';
import ReactHotToast from '../components/recoilQueryToast/ReactHotToast';


const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`h-screen ${inter.className} max-w-3xl mx-auto mb-0 px-4 flex flex-col justify-between`}>       

        <main className="mb-auto h-screen">
          <Recoil>
            <ReactQuery >{children}</ReactQuery>
          </Recoil>
          <ReactHotToast />
        </main>
        <Footer />
      </body>
    </html>
  )
}
