import '../components/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '../components/Footer';


//reactQuery recoil reactHotToast
import ReactQuery from '../components/recoilQueryToast/ReactQuery';
import Recoil from '../components/recoilQueryToast/Recoil';
import ReactHotToast from '../components/recoilQueryToast/ReactHotToast';


const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-3xl mx-auto flex flex-col min-h-screen`}>  
      <div className = 'container'>  
        <Recoil>
          <ReactQuery >{children}</ReactQuery>
        </Recoil>
        <ReactHotToast />
        </div>
        <Footer />
      </body>
    </html>
  )
}
